# Generated by Django 6.0.4 on 2026-04-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amdcpu',
            name='socket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='amdmotherboard',
            name='ram_type',
            field=models.CharField(default='DDR4', max_length=20),
        ),
        migrations.AddField(
            model_name='amdmotherboard',
            name='socket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='intelcpu',
            name='socket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='intelmotherboard',
            name='ram_type',
            field=models.CharField(default='DDR4', max_length=20),
        ),
        migrations.AddField(
            model_name='intelmotherboard',
            name='socket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='ram_type',
            field=models.CharField(default='DDR4', max_length=20),
        ),
    ]
