# Generated by Django 6.0.4 on 2026-04-20 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrebuiltPC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('gaming', 'Gaming'), ('editing', 'Video Editing'), ('design', 'Graphic Design')], default='gaming', max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
                ('platform', models.CharField(choices=[('intel', 'Intel'), ('amd', 'AMD')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amd_cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app0.amdcpu')),
                ('amd_motherboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app0.amdmotherboard')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app0.case')),
                ('cooler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app0.cooler')),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app0.gpu')),
                ('intel_cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app0.intelcpu')),
                ('intel_motherboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app0.intelmotherboard')),
                ('psu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app0.psu')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app0.ram')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app0.storage')),
            ],
        ),
    ]
