# Generated by Django 6.0.4 on 2026-04-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0005_prebuiltpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildsession',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
